<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- Package Metadata -->
        <PackageId>Atlas</PackageId>
        <Version>0.1.0</Version>
        <Authors>Muntadhar Haydar</Authors>
        <Company>Klaraa Labs Ltd</Company>
        <Description>Query compilation engine mapping structured JSON queries to Entity Framework Core IQueryable pipelines for building flexible, secure APIs.</Description>
        <PackageTags>query-engine;json;entity-framework-core;ef-core;linq;dotnet;aspnetcore;orm;api;security</PackageTags>
        <PackageProjectUrl>https://github.com/klaraalabs/atlas</PackageProjectUrl>
        <RepositoryUrl>https://github.com/klaraalabs/atlas</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    </ItemGroup>

</Project>
